// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: api/ocp-roadmap-api/ocp-roadmap-api.proto

package ocp_roadmap_api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Roadmap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId    uint64                 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Link      string                 `protobuf:"bytes,3,opt,name=link,proto3" json:"link,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
}

func (x *Roadmap) Reset() {
	*x = Roadmap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Roadmap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Roadmap) ProtoMessage() {}

func (x *Roadmap) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Roadmap.ProtoReflect.Descriptor instead.
func (*Roadmap) Descriptor() ([]byte, []int) {
	return file_api_ocp_roadmap_api_ocp_roadmap_api_proto_rawDescGZIP(), []int{0}
}

func (x *Roadmap) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Roadmap) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Roadmap) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Roadmap) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateRoadmapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roadmap *Roadmap `protobuf:"bytes,1,opt,name=roadmap,proto3" json:"roadmap,omitempty"`
}

func (x *CreateRoadmapRequest) Reset() {
	*x = CreateRoadmapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoadmapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoadmapRequest) ProtoMessage() {}

func (x *CreateRoadmapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoadmapRequest.ProtoReflect.Descriptor instead.
func (*CreateRoadmapRequest) Descriptor() ([]byte, []int) {
	return file_api_ocp_roadmap_api_ocp_roadmap_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoadmapRequest) GetRoadmap() *Roadmap {
	if x != nil {
		return x.Roadmap
	}
	return nil
}

type CreateRoadmapResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateRoadmapResponse) Reset() {
	*x = CreateRoadmapResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoadmapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoadmapResponse) ProtoMessage() {}

func (x *CreateRoadmapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoadmapResponse.ProtoReflect.Descriptor instead.
func (*CreateRoadmapResponse) Descriptor() ([]byte, []int) {
	return file_api_ocp_roadmap_api_ocp_roadmap_api_proto_rawDescGZIP(), []int{2}
}

type UpdateRoadmapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId    uint64                 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Link      string                 `protobuf:"bytes,3,opt,name=link,proto3" json:"link,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
}

func (x *UpdateRoadmapRequest) Reset() {
	*x = UpdateRoadmapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRoadmapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoadmapRequest) ProtoMessage() {}

func (x *UpdateRoadmapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoadmapRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoadmapRequest) Descriptor() ([]byte, []int) {
	return file_api_ocp_roadmap_api_ocp_roadmap_api_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateRoadmapRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRoadmapRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateRoadmapRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *UpdateRoadmapRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type UpdateRoadmapResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Updated bool `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
}

func (x *UpdateRoadmapResponse) Reset() {
	*x = UpdateRoadmapResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRoadmapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoadmapResponse) ProtoMessage() {}

func (x *UpdateRoadmapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoadmapResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoadmapResponse) Descriptor() ([]byte, []int) {
	return file_api_ocp_roadmap_api_ocp_roadmap_api_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRoadmapResponse) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

type MultiCreateRoadmapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roadmaps []*Roadmap `protobuf:"bytes,1,rep,name=roadmaps,proto3" json:"roadmaps,omitempty"`
}

func (x *MultiCreateRoadmapRequest) Reset() {
	*x = MultiCreateRoadmapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiCreateRoadmapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiCreateRoadmapRequest) ProtoMessage() {}

func (x *MultiCreateRoadmapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiCreateRoadmapRequest.ProtoReflect.Descriptor instead.
func (*MultiCreateRoadmapRequest) Descriptor() ([]byte, []int) {
	return file_api_ocp_roadmap_api_ocp_roadmap_api_proto_rawDescGZIP(), []int{5}
}

func (x *MultiCreateRoadmapRequest) GetRoadmaps() []*Roadmap {
	if x != nil {
		return x.Roadmaps
	}
	return nil
}

type MultiCreateRoadmapResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoadmapsIds []uint64 `protobuf:"varint,1,rep,packed,name=roadmaps_ids,json=roadmapsIds,proto3" json:"roadmaps_ids,omitempty"`
}

func (x *MultiCreateRoadmapResponse) Reset() {
	*x = MultiCreateRoadmapResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiCreateRoadmapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiCreateRoadmapResponse) ProtoMessage() {}

func (x *MultiCreateRoadmapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiCreateRoadmapResponse.ProtoReflect.Descriptor instead.
func (*MultiCreateRoadmapResponse) Descriptor() ([]byte, []int) {
	return file_api_ocp_roadmap_api_ocp_roadmap_api_proto_rawDescGZIP(), []int{6}
}

func (x *MultiCreateRoadmapResponse) GetRoadmapsIds() []uint64 {
	if x != nil {
		return x.RoadmapsIds
	}
	return nil
}

type DescribeRoadmapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DescribeRoadmapRequest) Reset() {
	*x = DescribeRoadmapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeRoadmapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRoadmapRequest) ProtoMessage() {}

func (x *DescribeRoadmapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRoadmapRequest.ProtoReflect.Descriptor instead.
func (*DescribeRoadmapRequest) Descriptor() ([]byte, []int) {
	return file_api_ocp_roadmap_api_ocp_roadmap_api_proto_rawDescGZIP(), []int{7}
}

func (x *DescribeRoadmapRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DescribeRoadmapResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roadmap *Roadmap `protobuf:"bytes,1,opt,name=roadmap,proto3" json:"roadmap,omitempty"`
}

func (x *DescribeRoadmapResponse) Reset() {
	*x = DescribeRoadmapResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeRoadmapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRoadmapResponse) ProtoMessage() {}

func (x *DescribeRoadmapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRoadmapResponse.ProtoReflect.Descriptor instead.
func (*DescribeRoadmapResponse) Descriptor() ([]byte, []int) {
	return file_api_ocp_roadmap_api_ocp_roadmap_api_proto_rawDescGZIP(), []int{8}
}

func (x *DescribeRoadmapResponse) GetRoadmap() *Roadmap {
	if x != nil {
		return x.Roadmap
	}
	return nil
}

type ListRoadmapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit  uint64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset uint64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *ListRoadmapRequest) Reset() {
	*x = ListRoadmapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRoadmapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoadmapRequest) ProtoMessage() {}

func (x *ListRoadmapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoadmapRequest.ProtoReflect.Descriptor instead.
func (*ListRoadmapRequest) Descriptor() ([]byte, []int) {
	return file_api_ocp_roadmap_api_ocp_roadmap_api_proto_rawDescGZIP(), []int{9}
}

func (x *ListRoadmapRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRoadmapRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListRoadmapResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roadmaps []*Roadmap `protobuf:"bytes,1,rep,name=roadmaps,proto3" json:"roadmaps,omitempty"`
}

func (x *ListRoadmapResponse) Reset() {
	*x = ListRoadmapResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRoadmapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoadmapResponse) ProtoMessage() {}

func (x *ListRoadmapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoadmapResponse.ProtoReflect.Descriptor instead.
func (*ListRoadmapResponse) Descriptor() ([]byte, []int) {
	return file_api_ocp_roadmap_api_ocp_roadmap_api_proto_rawDescGZIP(), []int{10}
}

func (x *ListRoadmapResponse) GetRoadmaps() []*Roadmap {
	if x != nil {
		return x.Roadmaps
	}
	return nil
}

type RemoveRoadmapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RemoveRoadmapRequest) Reset() {
	*x = RemoveRoadmapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveRoadmapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRoadmapRequest) ProtoMessage() {}

func (x *RemoveRoadmapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRoadmapRequest.ProtoReflect.Descriptor instead.
func (*RemoveRoadmapRequest) Descriptor() ([]byte, []int) {
	return file_api_ocp_roadmap_api_ocp_roadmap_api_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveRoadmapRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RemoveRoadmapResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Removed bool `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
}

func (x *RemoveRoadmapResponse) Reset() {
	*x = RemoveRoadmapResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveRoadmapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRoadmapResponse) ProtoMessage() {}

func (x *RemoveRoadmapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRoadmapResponse.ProtoReflect.Descriptor instead.
func (*RemoveRoadmapResponse) Descriptor() ([]byte, []int) {
	return file_api_ocp_roadmap_api_ocp_roadmap_api_proto_rawDescGZIP(), []int{12}
}

func (x *RemoveRoadmapResponse) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

var File_api_ocp_roadmap_api_ocp_roadmap_api_proto protoreflect.FileDescriptor

var file_api_ocp_roadmap_api_ocp_roadmap_api_proto_rawDesc = []byte{
	0x0a, 0x29, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x72, 0x6f, 0x61, 0x64, 0x6d, 0x61,
	0x70, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x72, 0x6f, 0x61, 0x64, 0x6d, 0x61,
	0x70, 0x2d, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6f, 0x63, 0x70,
	0x2e, 0x72, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x2e, 0x61, 0x70, 0x69, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7f, 0x0a, 0x07, 0x52,
	0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69,
	0x6e, 0x6b, 0x12, 0x38, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x4a, 0x0a, 0x14,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x07, 0x72, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x72, 0x6f, 0x61, 0x64,
	0x6d, 0x61, 0x70, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x52,
	0x07, 0x72, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x22, 0x17, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x8c, 0x01, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x61, 0x64,
	0x6d, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x38, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x22, 0x31, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x61, 0x64, 0x6d, 0x61,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x22, 0x51, 0x0a, 0x19, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x34, 0x0a, 0x08, 0x72, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x72, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x52, 0x08, 0x72, 0x6f,
	0x61, 0x64, 0x6d, 0x61, 0x70, 0x73, 0x22, 0x3f, 0x0a, 0x1a, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x73,
	0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x0b, 0x72, 0x6f, 0x61, 0x64,
	0x6d, 0x61, 0x70, 0x73, 0x49, 0x64, 0x73, 0x22, 0x28, 0x0a, 0x16, 0x44, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x52, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x4d, 0x0a, 0x17, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x6f, 0x61,
	0x64, 0x6d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x07,
	0x72, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x6f, 0x63, 0x70, 0x2e, 0x72, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x52, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x52, 0x07, 0x72, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70,
	0x22, 0x42, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x22, 0x4b, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x61, 0x64,
	0x6d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x08, 0x72,
	0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x6f, 0x63, 0x70, 0x2e, 0x72, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x52, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x52, 0x08, 0x72, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70,
	0x73, 0x22, 0x26, 0x0a, 0x14, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x6f, 0x61, 0x64, 0x6d,
	0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x31, 0x0a, 0x15, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x52, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x32, 0xe5, 0x05, 0x0a,
	0x0d, 0x4f, 0x63, 0x70, 0x52, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x41, 0x70, 0x69, 0x12, 0x73,
	0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x12,
	0x25, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x72, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x72, 0x6f, 0x61,
	0x64, 0x6d, 0x61, 0x70, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x13,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0d, 0x22, 0x08, 0x2f, 0x72, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70,
	0x3a, 0x01, 0x2a, 0x12, 0x84, 0x01, 0x0a, 0x13, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x73, 0x12, 0x2a, 0x2e, 0x6f, 0x63,
	0x70, 0x2e, 0x72, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x75,
	0x6c, 0x74, 0x69, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x72, 0x6f,
	0x61, 0x64, 0x6d, 0x61, 0x70, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x22, 0x09, 0x2f, 0x72,
	0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x73, 0x3a, 0x01, 0x2a, 0x12, 0x78, 0x0a, 0x0d, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x12, 0x25, 0x2e, 0x6f, 0x63,
	0x70, 0x2e, 0x72, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x26, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x72, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x61, 0x64, 0x6d,
	0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x12, 0x1a, 0x0d, 0x2f, 0x72, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x2f, 0x7b, 0x69, 0x64,
	0x7d, 0x3a, 0x01, 0x2a, 0x12, 0x7b, 0x0a, 0x0f, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x52, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x12, 0x27, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x72, 0x6f,
	0x61, 0x64, 0x6d, 0x61, 0x70, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x52, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x28, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x72, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x6f, 0x61, 0x64, 0x6d,
	0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x0f, 0x12, 0x0d, 0x2f, 0x72, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x2f, 0x7b, 0x69, 0x64,
	0x7d, 0x12, 0x6a, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70,
	0x12, 0x23, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x72, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x72, 0x6f, 0x61, 0x64,
	0x6d, 0x61, 0x70, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x61, 0x64,
	0x6d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x10, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x0a, 0x12, 0x08, 0x2f, 0x72, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x12, 0x75, 0x0a,
	0x0d, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x12, 0x25,
	0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x72, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x72, 0x6f, 0x61, 0x64,
	0x6d, 0x61, 0x70, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x6f,
	0x61, 0x64, 0x6d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x15, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x2a, 0x0d, 0x2f, 0x72, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x2f,
	0x7b, 0x69, 0x64, 0x7d, 0x42, 0x47, 0x5a, 0x45, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6f, 0x7a, 0x6f, 0x6e, 0x63, 0x70, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x72, 0x6f,
	0x61, 0x64, 0x6d, 0x61, 0x70, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6f, 0x63,
	0x70, 0x2d, 0x72, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x2d, 0x61, 0x70, 0x69, 0x3b, 0x6f, 0x63,
	0x70, 0x5f, 0x72, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_ocp_roadmap_api_ocp_roadmap_api_proto_rawDescOnce sync.Once
	file_api_ocp_roadmap_api_ocp_roadmap_api_proto_rawDescData = file_api_ocp_roadmap_api_ocp_roadmap_api_proto_rawDesc
)

func file_api_ocp_roadmap_api_ocp_roadmap_api_proto_rawDescGZIP() []byte {
	file_api_ocp_roadmap_api_ocp_roadmap_api_proto_rawDescOnce.Do(func() {
		file_api_ocp_roadmap_api_ocp_roadmap_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_ocp_roadmap_api_ocp_roadmap_api_proto_rawDescData)
	})
	return file_api_ocp_roadmap_api_ocp_roadmap_api_proto_rawDescData
}

var file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_ocp_roadmap_api_ocp_roadmap_api_proto_goTypes = []interface{}{
	(*Roadmap)(nil),                    // 0: ocp.roadmap.api.Roadmap
	(*CreateRoadmapRequest)(nil),       // 1: ocp.roadmap.api.CreateRoadmapRequest
	(*CreateRoadmapResponse)(nil),      // 2: ocp.roadmap.api.CreateRoadmapResponse
	(*UpdateRoadmapRequest)(nil),       // 3: ocp.roadmap.api.UpdateRoadmapRequest
	(*UpdateRoadmapResponse)(nil),      // 4: ocp.roadmap.api.UpdateRoadmapResponse
	(*MultiCreateRoadmapRequest)(nil),  // 5: ocp.roadmap.api.MultiCreateRoadmapRequest
	(*MultiCreateRoadmapResponse)(nil), // 6: ocp.roadmap.api.MultiCreateRoadmapResponse
	(*DescribeRoadmapRequest)(nil),     // 7: ocp.roadmap.api.DescribeRoadmapRequest
	(*DescribeRoadmapResponse)(nil),    // 8: ocp.roadmap.api.DescribeRoadmapResponse
	(*ListRoadmapRequest)(nil),         // 9: ocp.roadmap.api.ListRoadmapRequest
	(*ListRoadmapResponse)(nil),        // 10: ocp.roadmap.api.ListRoadmapResponse
	(*RemoveRoadmapRequest)(nil),       // 11: ocp.roadmap.api.RemoveRoadmapRequest
	(*RemoveRoadmapResponse)(nil),      // 12: ocp.roadmap.api.RemoveRoadmapResponse
	(*timestamppb.Timestamp)(nil),      // 13: google.protobuf.Timestamp
}
var file_api_ocp_roadmap_api_ocp_roadmap_api_proto_depIdxs = []int32{
	13, // 0: ocp.roadmap.api.Roadmap.createdAt:type_name -> google.protobuf.Timestamp
	0,  // 1: ocp.roadmap.api.CreateRoadmapRequest.roadmap:type_name -> ocp.roadmap.api.Roadmap
	13, // 2: ocp.roadmap.api.UpdateRoadmapRequest.createdAt:type_name -> google.protobuf.Timestamp
	0,  // 3: ocp.roadmap.api.MultiCreateRoadmapRequest.roadmaps:type_name -> ocp.roadmap.api.Roadmap
	0,  // 4: ocp.roadmap.api.DescribeRoadmapResponse.roadmap:type_name -> ocp.roadmap.api.Roadmap
	0,  // 5: ocp.roadmap.api.ListRoadmapResponse.roadmaps:type_name -> ocp.roadmap.api.Roadmap
	1,  // 6: ocp.roadmap.api.OcpRoadmapApi.CreateRoadmap:input_type -> ocp.roadmap.api.CreateRoadmapRequest
	5,  // 7: ocp.roadmap.api.OcpRoadmapApi.MultiCreateRoadmaps:input_type -> ocp.roadmap.api.MultiCreateRoadmapRequest
	3,  // 8: ocp.roadmap.api.OcpRoadmapApi.UpdateRoadmap:input_type -> ocp.roadmap.api.UpdateRoadmapRequest
	7,  // 9: ocp.roadmap.api.OcpRoadmapApi.DescribeRoadmap:input_type -> ocp.roadmap.api.DescribeRoadmapRequest
	9,  // 10: ocp.roadmap.api.OcpRoadmapApi.ListRoadmap:input_type -> ocp.roadmap.api.ListRoadmapRequest
	11, // 11: ocp.roadmap.api.OcpRoadmapApi.RemoveRoadmap:input_type -> ocp.roadmap.api.RemoveRoadmapRequest
	2,  // 12: ocp.roadmap.api.OcpRoadmapApi.CreateRoadmap:output_type -> ocp.roadmap.api.CreateRoadmapResponse
	6,  // 13: ocp.roadmap.api.OcpRoadmapApi.MultiCreateRoadmaps:output_type -> ocp.roadmap.api.MultiCreateRoadmapResponse
	4,  // 14: ocp.roadmap.api.OcpRoadmapApi.UpdateRoadmap:output_type -> ocp.roadmap.api.UpdateRoadmapResponse
	8,  // 15: ocp.roadmap.api.OcpRoadmapApi.DescribeRoadmap:output_type -> ocp.roadmap.api.DescribeRoadmapResponse
	10, // 16: ocp.roadmap.api.OcpRoadmapApi.ListRoadmap:output_type -> ocp.roadmap.api.ListRoadmapResponse
	12, // 17: ocp.roadmap.api.OcpRoadmapApi.RemoveRoadmap:output_type -> ocp.roadmap.api.RemoveRoadmapResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_ocp_roadmap_api_ocp_roadmap_api_proto_init() }
func file_api_ocp_roadmap_api_ocp_roadmap_api_proto_init() {
	if File_api_ocp_roadmap_api_ocp_roadmap_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Roadmap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoadmapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoadmapResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRoadmapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRoadmapResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiCreateRoadmapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiCreateRoadmapResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeRoadmapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeRoadmapResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRoadmapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRoadmapResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveRoadmapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveRoadmapResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_ocp_roadmap_api_ocp_roadmap_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ocp_roadmap_api_ocp_roadmap_api_proto_goTypes,
		DependencyIndexes: file_api_ocp_roadmap_api_ocp_roadmap_api_proto_depIdxs,
		MessageInfos:      file_api_ocp_roadmap_api_ocp_roadmap_api_proto_msgTypes,
	}.Build()
	File_api_ocp_roadmap_api_ocp_roadmap_api_proto = out.File
	file_api_ocp_roadmap_api_ocp_roadmap_api_proto_rawDesc = nil
	file_api_ocp_roadmap_api_ocp_roadmap_api_proto_goTypes = nil
	file_api_ocp_roadmap_api_ocp_roadmap_api_proto_depIdxs = nil
}
